//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV.POS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashboxTestify
    {
        public Nullable<byte> CashboxId { get; set; }
        public int CashboxTestifyId { get; set; }
        public System.DateTime TestifyDate { get; set; }
        public Nullable<short> UserId { get; set; }
        public Nullable<decimal> AmountChecked { get; set; }
        public Nullable<decimal> Difference { get; set; }
        public Nullable<int> SessionId { get; set; }
        public Nullable<int> CBStatusId { get; set; }
    
        public virtual CashboxStatus CashboxStatus { get; set; }
        public virtual Session Session { get; set; }
    }
}
