//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV.POS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashboxStatus
    {
        public CashboxStatus()
        {
            this.CashboxTestify = new HashSet<CashboxTestify>();
        }
    
        public int CBStatusId { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public decimal StartAmount { get; set; }
        public Nullable<decimal> EndAmount { get; set; }
        public Nullable<byte> CashboxId { get; set; }
        public Nullable<short> UserId { get; set; }
    
        public virtual Cashbox Cashbox { get; set; }
        public virtual ICollection<CashboxTestify> CashboxTestify { get; set; }
    }
}
