//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV.POS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashMovement
    {
        public CashMovement()
        {
            this.Sale = new HashSet<Sale>();
        }
    
        public byte CashboxId { get; set; }
        public int CashMovementId { get; set; }
        public System.DateTime MovementDate { get; set; }
        public decimal Amount { get; set; }
        public string MovementType { get; set; }
        public string MovementStatus { get; set; }
        public int SessionId { get; set; }
        public string MovementCategory { get; set; }
    
        public virtual Cashbox Cashbox { get; set; }
        public virtual Session Session { get; set; }
        public virtual ICollection<Sale> Sale { get; set; }
    }
}
