//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV.POS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.Division = new HashSet<Division>();
        }
    
        public byte CompanyId { get; set; }
        public string Name { get; set; }
        public string RUC { get; set; }
        public string Address { get; set; }
    
        public virtual ICollection<Division> Division { get; set; }
    }
}
