//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV.POS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.SaleDocument = new HashSet<SaleDocument>();
        }
    
        public Nullable<int> PersonId { get; set; }
        public int CustomerId { get; set; }
        public string RUC { get; set; }
        public string LegalName { get; set; }
        public string CustomerType { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual ICollection<SaleDocument> SaleDocument { get; set; }
    }
}
