//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV.POS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Division
    {
        public Division()
        {
            this.Premise = new HashSet<Premise>();
        }
    
        public byte DivisionId { get; set; }
        public Nullable<byte> CompanyId { get; set; }
        public string Name { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ICollection<Premise> Premise { get; set; }
    }
}
