//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV.POS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.User = new HashSet<User>();
        }
    
        public int EmployeeId { get; set; }
        public Nullable<int> PersonId { get; set; }
    
        public virtual ICollection<User> User { get; set; }
        public virtual Person Person { get; set; }
    }
}
