//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV.POS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Premise
    {
        public Premise()
        {
            this.Cashbox = new HashSet<Cashbox>();
            this.ProductPremise = new HashSet<ProductPremise>();
            this.Session = new HashSet<Session>();
            this.ProductMovement = new HashSet<ProductMovement>();
        }
    
        public Nullable<byte> DivisionId { get; set; }
        public byte PremiseId { get; set; }
        public string Address { get; set; }
        public string Name { get; set; }
        public string PremiseType { get; set; }
    
        public virtual ICollection<Cashbox> Cashbox { get; set; }
        public virtual Division Division { get; set; }
        public virtual ICollection<ProductPremise> ProductPremise { get; set; }
        public virtual ICollection<Session> Session { get; set; }
        public virtual ICollection<ProductMovement> ProductMovement { get; set; }
    }
}
