//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV.POS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ProductUnit = new HashSet<ProductUnit>();
            this.ProductPremise = new HashSet<ProductPremise>();
        }
    
        public Nullable<short> ProductBaseId { get; set; }
        public int ProductId { get; set; }
        public Nullable<byte> MiscVariantId { get; set; }
    
        public virtual MiscVariant MiscVariant { get; set; }
        public virtual ICollection<ProductUnit> ProductUnit { get; set; }
        public virtual ProductBase ProductBase { get; set; }
        public virtual ICollection<ProductPremise> ProductPremise { get; set; }
    }
}
