//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV.POS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPremise
    {
        public ProductPremise()
        {
            this.ProductPremiseStatus = new HashSet<ProductPremiseStatus>();
        }
    
        public int ProductId { get; set; }
        public byte PremiseId { get; set; }
        public Nullable<int> CurrentStock { get; set; }
        public Nullable<int> MinimunStock { get; set; }
        public string StockDefaultUnitAbbr { get; set; }
    
        public virtual Premise Premise { get; set; }
        public virtual Product Product { get; set; }
        public virtual ICollection<ProductPremiseStatus> ProductPremiseStatus { get; set; }
    }
}
