//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV.POS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPremiseStatus
    {
        public int PPStatusId { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> StartQuantity { get; set; }
        public Nullable<int> EndQuantity { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<byte> PremiseId { get; set; }
    
        public virtual ProductPremise ProductPremise { get; set; }
    }
}
