//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV.POS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductUnit
    {
        public int ProductId { get; set; }
        public byte UnitId { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public decimal SalePrice { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
