//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV.POS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductMovement
    {
        public ProductMovement()
        {
            this.SaleDetails = new HashSet<SaleDetails>();
        }
    
        public int ProductMovementId { get; set; }
        public byte PremiseId { get; set; }
        public string MovementType { get; set; }
        public string MovementCategory { get; set; }
        public int ProductId { get; set; }
        public byte UnitId { get; set; }
        public int Quantity { get; set; }
        public System.DateTime MovementDate { get; set; }
        public int SessionId { get; set; }
    
        public virtual Premise Premise { get; set; }
        public virtual ICollection<SaleDetails> SaleDetails { get; set; }
    }
}
