//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV.POS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int SaleId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Status { get; set; }
        public Nullable<int> SessionId { get; set; }
        public Nullable<int> CashMovementId { get; set; }
    
        public virtual CashMovement CashMovement { get; set; }
        public virtual SaleDocument SaleDocument { get; set; }
        public virtual Session Session { get; set; }
    }
}
