//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV.POS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleDocument
    {
        public SaleDocument()
        {
            this.SaleDetails = new HashSet<SaleDetails>();
        }
    
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string RUC { get; set; }
        public string Status { get; set; }
        public string Number { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> IGV { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string DocumentType { get; set; }
        public int SaleId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Sale Sale { get; set; }
        public virtual ICollection<SaleDetails> SaleDetails { get; set; }
    }
}
