//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV.POS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleDetails
    {
        public int SaleDetailId { get; set; }
        public Nullable<short> Quantity { get; set; }
        public Nullable<decimal> SinglePrice { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<int> SaleId { get; set; }
        public Nullable<int> ProductMovementId { get; set; }
    
        public virtual ProductMovement ProductMovement { get; set; }
        public virtual SaleDocument SaleDocument { get; set; }
    }
}
