//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV.POS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemRole
    {
        public SystemRole()
        {
            this.User = new HashSet<User>();
        }
    
        public byte RoleId { get; set; }
        public string RoleName { get; set; }
    
        public virtual ICollection<User> User { get; set; }
    }
}
