//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV.POS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitEquivalence
    {
        public byte UnitEquivalenceId { get; set; }
        public string LowerUnitAbbr { get; set; }
        public string HigherUnitAbbr { get; set; }
        public int EquivalenceFactor { get; set; }
    }
}
