//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV.POS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Session = new HashSet<Session>();
            this.SystemRole = new HashSet<SystemRole>();
        }
    
        public Nullable<int> EmployeeId { get; set; }
        public short UserId { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public byte DefaultPremise { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ICollection<Session> Session { get; set; }
        public virtual ICollection<SystemRole> SystemRole { get; set; }
    }
}
