//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using CV.POS.Entities;

namespace CV.POS.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PosDbContext : DbContext
    {
        public PosDbContext()
            : base("name=PosDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cashbox> Cashbox { get; set; }
        public DbSet<CashboxStatus> CashboxStatus { get; set; }
        public DbSet<CashboxTestify> CashboxTestify { get; set; }
        public DbSet<CashMovement> CashMovement { get; set; }
        public DbSet<Company> Company { get; set; }
        public DbSet<Customer> Customer { get; set; }
        public DbSet<Division> Division { get; set; }
        public DbSet<Employee> Employee { get; set; }
        public DbSet<GeneralConfigValues> GeneralConfigValues { get; set; }
        public DbSet<MiscVariant> MiscVariant { get; set; }
        public DbSet<Person> Person { get; set; }
        public DbSet<Premise> Premise { get; set; }
        public DbSet<Product> Product { get; set; }
        public DbSet<ProductBase> ProductBase { get; set; }
        public DbSet<ProductMovement> ProductMovement { get; set; }
        public DbSet<ProductPremise> ProductPremise { get; set; }
        public DbSet<ProductPremiseStatus> ProductPremiseStatus { get; set; }
        public DbSet<ProductUnit> ProductUnit { get; set; }
        public DbSet<Sale> Sale { get; set; }
        public DbSet<SaleDetails> SaleDetails { get; set; }
        public DbSet<SaleDocument> SaleDocument { get; set; }
        public DbSet<Session> Session { get; set; }
        public DbSet<SystemRole> SystemRole { get; set; }
        public DbSet<Unit> Unit { get; set; }
        public DbSet<UnitEquivalence> UnitEquivalence { get; set; }
        public DbSet<User> User { get; set; }
    }
}
